- hosts: prod
  vars:
  - image: ioez1984/signew

  tasks:
    - name: install python-docker centos
      yum:
        name:
          - python
          - python-docker
        state: present
    - name: pull image docker
      docker_image:
        name: "{{ image }}"
        state: present
        force: yes
    - name: create containers
      docker_container:
        name: signew-byjenkins
        image: "{{ image }}"
        state: started
        restart_policy: always
        published_ports:
        - 80:80
        recreate: yes
    - name: cleanup dangling images
      shell: |
        oldimage=`docker images | grep '<none>' | awk '{print $3}'`
        if [ -z "$oldimage" ]
        then
        echo "There is no dangling images found!"
        else
        docker rmi ${oldimage} -f
        fi

      ignore_errors: yes
      become: true
